language: node_js

node_js:
  - "9"

sudo: false

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn global add codecov
  - yarn run test
  - bash <(curl -s https://codecov.io/bash)